[Youtube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "latest"
excluded-patches = "custom-branding disable-shorts-on-startup disable-fullscreen-panels disable-player-popup-panels hide-shorts-components hide-album-cards hide-autoplay-button hide-captions-button hide-cast-button hide-crowdfunding-box hide-email-address hide-endscreen-cards hide-filter-bar hide-floating-microphone-button hide-info-cards hide-layout-components hide-load-more-button hide-player-buttons hide-player-overlay hide-seekbar hide-timestamp hide-video-action-buttons hide-watch-in-vr"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

