[Metube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "disable-fullscreen-panels disable-player-popup-panels hide-shorts-components hide-album-cards hide-captions-button hide-cast-button hide-info-cards hide-timestamp tablet-mini-player"
